### ISSUE TITLE
Default spinner

### ISSUE THREAD

**Issue by korontari** [BWPanda/featherlight#5]
Would be great to have some defaut spinner as Loading content. For a generic user (like me) it may not be obvious how to assign a spinner into "Loading" option field on settings page. All I can do is just put some text there. :)

**Comment by ghost** [comment]
Since this module doesn't ship with any custom styling, I don't really want to add some now (it's up to people installing this module to theme Featherlight the way they want). This includes a spinner. There's two great CSS-only methods described here: https://github.com/noelboss/featherlight/wiki/Add-a-CSS-Only-Loader I'd suggest using one of those.

**Comment by korontari** [comment]
I understand you. I just was thinking of giving some customisation options for users that do not code. 
Would you be interested in adding some custom styles to the module so that user can select them in module settings (like in Colorbox module)?  I could probably try and create some styles for the Featherlight, as I have some basic knowlege of CSS. Let me know what you think.

**Comment by ghost** [comment]
Thanks for the suggestion/offer. If there's other interest in this, I'll consider it. But for now I like the minimalist approach of this module.

**Comment by ghost** [comment]
Since the other issue adds CSS then I'm more open to adding CSS for this too. PR attached, please test and let me know what you think.

**Comment by korontari** [comment]
Oh, I think having this spinner by default is way better! Thank you! Good to have it right out of the box and yet offers customization if needed. I like this.

**Comment by ghost** [comment]
Committed PR.
